# An Advanced Guide to Trade Policy Analysis: The Structural Gravity Model
# Chapter 2: General Equilibrium Trade Policy Analysis with Structural Gravity
# Application 2: IMPACT OF REGIONAL TRADE AGREEMENTS
# Last update: 2021/04/26

# Load packages -----------------------------------------------------------
library(haven)
library(dplyr)
library(ggplot2)
library(estimatr)
library(lmtest)
library(fixest)
library(nleqslv)
library(janitor)

# Function for general equilibrium analysis
source("R/ge_functions.R", encoding = "UTF-8")
# Function for a custom ppml estimator
source("R/aux_functions.R", encoding = "UTF-8")

# Load the data ----------------------------------------------------------------

data_nafta <- read_dta("Data/Chapter2Application2.dta") %>%
  clean_names()

data_nafta <- data_nafta %>%
  mutate(
    exporter = ifelse(exporter == "DEU", "AAA", exporter),
    importer = ifelse(importer == "DEU", "AAA", importer),
    ln_dist = log(dist),
    intl = ifelse(exporter != importer, 1, 0)
  ) %>%
  filter(year %in% seq(1986, 2006, 4)) %>%
  group_by(importer, year) %>%
  # e = expenditure
  mutate(e = sum(trade)) %>%
  ungroup() %>%
  group_by(exporter, year) %>%
  # y = production
  mutate(y = sum(trade)) %>%
  ungroup() %>%
  group_by(year) %>%
  mutate(
    e_r_bln = ifelse(importer == "AAA", e, 0),
    e_r = max(e_r_bln),
    exp_year = paste0(exporter, year),
    imp_year = paste0(importer, year),
    pair_id2 = ifelse(exporter == importer, "intra", pair_id)
  ) %>%
  ungroup()

# Sum of trade by pair - all years
data_nafta <- data_nafta %>%
  group_by(pair_id) %>%
  mutate(sum_trade = sum(trade)) %>%
  ungroup() %>%
  arrange(exporter, pair_id2, importer)

# Step 1: Solve the baseline gravity model --------------------------------

# For some reason, in the case of three fixed effects, the values of the fixed
# effects computed by the fixest package are different from those generated by
# STATA. For this reason, we will use a custom function.
# fit <- fepois(
#   trade ~ rta | exp_year + imp_year + pair_id2,
#   data = data_nafta %>% filter(sum_trade > 0),
#   cluster = ~ pair_id,
#   # adj = FALSE to compute the same standard-errors of the gravity_ppml function
#   ssc = ssc(adj = FALSE)
# )

# fit

# Stage 1: Obtain the estimates of pair fixed effects and RTAs

fit <- gravity_ppml(
  y = "trade",
  x = "rta",
  data = data_nafta %>% filter(sum_trade > 0),
  fixed_effects = c("imp_year", "exp_year", "pair_id2"),
  robust = TRUE,
  cluster = "pair_id"
)

# Get the fixed effects
data_nafta <- data_nafta %>%
  left_join(
    y = fit$fixed.effects,
    by = c("imp_year", "exp_year", "pair_id2")
  )

# Generate trade costs
data_nafta <- data_nafta %>%
  mutate(
    tij_bar = exp(fe_pair_id2),
    tij_bln = exp(fe_pair_id2 + fit$coefficients["rta",1] * rta)
  )

# Stage 2: predict trade costs for the pairs with zero trade flows
data_stage2 <- data_nafta %>%
  filter(year == 1994, exporter != importer) %>%
  mutate(tij = exp(fe_pair_id2))

fit_stage2 <- glm(tij ~ ln_dist + cntg + lang + clny + importer + exporter - 1,
  data = data_stage2, family = quasipoisson()
)

data_stage2$tij_norta <- predict(
  fit_stage2,
  newdata = data_stage2,
  type = "response"
)

data_stage2 <- data_stage2 %>%
  select(exporter, importer, tij_norta)

data_nafta <- data_nafta %>%
  filter(year == 1994) %>%
  left_join(
    data_stage2,
    by = c("exporter", "importer")
  ) %>%
  mutate(
    tij_bar = ifelse(is.na(tij_bar), tij_norta, tij_bar),
    tij_bln = ifelse(
      is.na(tij_bln),
      tij_bar * exp(fit$coefficients["rta",1] * rta),
      tij_bln
    )
  ) %>%
  select(-tij_norta) %>%
  mutate(ln_tij_bln = log(tij_bln)) %>%
  arrange(exporter, importer)

# Estimate trade on "constrained" trade costs

fit_bln <- gravity_ppml(
  y = "trade",
  x = NULL,
  fixed_effects = c("importer", "exporter"),
  offset = data_nafta$ln_tij_bln,
  data = data_nafta
)

data_nafta <- data_nafta %>%
  mutate(tradehat_bln = as.vector(fit_bln$fitted.values))

# Step 2: Define a couterfactual scenario -------------------------------------

# RTA = 0 if pair in NAFTA

nafta <- c("CAN", "MEX", "USA")
data_nafta <- data_nafta %>%
  mutate(
    rta_no_nafta = ifelse(
      exporter %in% nafta & importer %in% nafta,
      0,
      rta
    ),
    tij_cfl = tij_bar * exp(fit$coefficients["rta",1] * rta_no_nafta),
    ln_tij_cfl = log(tij_cfl)
  ) %>%
  arrange(exporter, importer)

# Compute Y, E, Q, phi, trade costs (tc) and alpha -----------------------------

Y <- data_nafta %>%
  group_by(exporter) %>%
  summarise(Y = sum(trade), .groups = "drop") %>%
  pull(Y)

E <- data_nafta %>%
  group_by(importer) %>%
  summarise(E = sum(trade), .groups = "drop") %>%
  pull(E)

Q <- Y

phi <- E / Q

N <- sqrt(nrow(data_nafta))

X <- data_nafta %>%
  pull(tradehat_bln)
X <- matrix(X, N, byrow = TRUE)

sigma <- 7

tc_bln <- matrix(data_nafta$tij_bln, nrow = N, byrow = TRUE)^(1 / (1 - sigma))
tc_cfl <- matrix(data_nafta$tij_cfl, nrow = N, byrow = TRUE)^(1 / (1 - sigma))

# alpha <- exp(fixef(fit_bln)$exporter)^(1 / (1 - sigma))
fe_importer <- fit_bln$fixed.effects %>%
  select(importer, fe_importer) %>% 
  distinct() %>% 
  pull(fe_importer)

P <- (E / exp(fe_importer))^(1 / (1 - sigma))
P <- P / P[1]
PI <- P
for(i in 1:N){
  PI[i] <- sum((tc_bln[i, ] / P)^(1 - sigma) * E / sum(Y))^(1 / (1 - sigma))
}

alpha <- (Y/sum(Y))^(1/(1-sigma)) * 1/PI

# Compute  - Baseline ----------------------------------------------------------

vars_bln <- ge_gravity(phi, Q, alpha, tc_bln, N, full_endowment = TRUE)
P_bln <- vars_bln$P
PI_bln <- vars_bln$PI
RGDP_bln <- vars_bln$RGDP
p_bln <- vars_bln$p
exp_bln <- rowSums(vars_bln$X) - diag(vars_bln$X)

# Partial effects on trade -----------------------------------------------------
X_par <- X * (tc_cfl^(1 - sigma)) /( tc_bln^(1 - sigma))
exp_par <- rowSums(X_par) - diag(X_par)

# Compute  - Conditional  ------------------------------------------------------
vars_cdl <- ge_gravity(phi, Q, alpha, tc_cfl, N, full_endowment = FALSE)
exp_cdl <- rowSums(vars_cdl$X) - diag(vars_cdl$X)

# Compute: Counterfactual ------------------------------------------------------
vars_cfl <- ge_gravity(phi, Q, alpha, tc_cfl, N, full_endowment = TRUE)
P_cfl <- vars_cfl$P
PI_cfl <- vars_cfl$PI
RGDP_cfl <- vars_cfl$RGDP
p_cfl <- vars_cfl$p
exp_cfl <- rowSums(vars_cfl$X) - diag(vars_cfl$X)

# Results summary --------------------------------------------------------------
data_nafta %>%
  select(exporter) %>%
  distinct() %>%
  mutate(
    country = ifelse(exporter == "AAA", "DEU", exporter),
    p_bln = p_bln,
    P_bln = P_bln,
    PI_bln = PI_bln,
    RGDP_bln = RGDP_bln,
    exp_bln = exp_bln,
    exp_par = exp_par,
    exp_cdl = exp_cdl,
    p_cfl = p_cfl,
    P_cfl = P_cfl,
    PI_cfl = PI_cfl,
    RGDP_cfl = RGDP_cfl,
    exp_cfl = exp_cfl
  ) %>% 
  arrange(country) %>% 
  mutate(
    chng_exp_par = round((exp_bln / exp_par - 1) * 100, 2),
    chng_exp_cdl = round((exp_bln / exp_cdl - 1) * 100, 2),
    chng_exp_cfl = round((exp_bln / exp_cfl - 1) * 100, 2),
    chng_RGDP = round((RGDP_bln / RGDP_cfl - 1) * 100, 2),
    chng_IMR = round((P_bln / P_cfl - 1) * 100, 2),
    chng_OMR = round((PI_bln / PI_cfl - 1) * 100, 2),
    chng_p = round((p_bln / p_cfl - 1) * 100, 2)
  ) %>% 
  select(country, starts_with("chng")) %>%
  as.data.frame()

